name: docs deploy


on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: 3.10.4
      - run: |
          python -m pip install poetry
          python -m pip install poetry-plugin-export
          poetry export -f requirements.txt --output requirements.txt --with dev --without-hashes
          python -m pip install -r requirements.txt # for some reason it is not installed by poetry
          mkdocs gh-deploy --force
          rm requirements.txt
